module.exports = [{
    id: 0,
    name: 'Mary Danko',
    phone: '8845579923',
    email: 'marydanko@example.com',
    relation: 'family',
    invited: ' ',
}, {
    id: 1,
    name: 'Tommy Curtin',
    phone: '7044439912',
    email: 'tommycurtin@example.com',
    relation: 'friend',
    invited: ' ',
}, {
    id: 2,
    name: 'Reece Belmondo',
    phone: '8675309911',
    email: 'reecebelmondo@example.com',
    relation: 'friend',
    invited: ' ',
}, {
    id: 3,
    name: 'Darby Enright',
    phone: '1234449955',
    email: 'darbyenright@example.com',
    relation: 'friend',
    invited: ' ',
}, {
    id: 4,
    name: 'Elizabeth Hall',
    phone: '8850912444',
    email: 'elizabethhall@example.com',
    relation: 'family',
    invited: ' ',
}, {
    id: 5,
    name: 'Jerry Danko',
    phone: '7046671896',
    email: 'jerrydanko@example.com',
    relation: 'family',
    invited: ' ',
}, {
    id: 6,
    name: 'Johnny Ive',
    phone: '9802216529',
    email: 'johnnyive@example.com',
    relation: 'friend',
    invited: ' ',
}, {
    id: 7,
    name: 'Tim Cook',
    phone: '1127440915',
    email: 'timcook@example.com',
    relation: 'friend',
    invited: ' ',
}, {
    id: 8,
    name: 'Steve Goebel',
    phone: '7752180032',
    email: 'stevegoebel@example.com',
    relation: 'friend',
    invited: ' ',
}];
