module.exports = [{
    id: 0,
    name: 'John Cena',
    phone: '8845579923',
    email: 'johncena@example.com',
    relation: ' ',
    invited: ' ',
}, {
    id: 1,
    name: 'Tommy Curtin',
    phone: '7044439912',
    email: 'tommycurtin@example.com',
    relation: ' ',
    invited: ' ',
}, {
    id: 2,
    name: 'Reece Belmondo',
    phone: '8675309911',
    email: 'reecebelmondo@example.com',
    relation: ' ',
    invited: ' ',
}, {
    id: 3,
    name: 'Marshall Mathers',
    phone: '1234449955',
    email: 'marshallmathers@example.com',
    relation: ' ',
    invited: ' ',
}, {
    id: 4,
    name: 'Steve Ballmer',
    phone: '8850912444',
    email: 'steveballmer@example.com',
    relation: ' ',
    invited: ' ',
}, {
    id: 5,
    name: 'Mark Cuban',
    phone: '7046671896',
    email: 'markcuban@example.com',
    relation: ' ',
    invited: ' ',
}, {
    id: 6,
    name: 'Johnny Ive',
    phone: '9802216529',
    email: 'johnnyive@example.com',
    relation: ' ',
    invited: ' ',
}, {
    id: 7,
    name: 'Tim Cook',
    phone: '1127440915',
    email: 'timcook@example.com',
    relation: ' ',
    invited: ' ',
}, {
    id: 8,
    name: 'Steve Goebel',
    phone: '7752180032',
    email: 'stevegoebel@example.com',
    relation: ' ',
    invited: " "
},  {
    id: 9,
    name: 'Yogi Berra',
    phone: '3825410938',
    email: 'yogitheberra@example.com',
    relation: ' ',
    invited: ' ',
},  {
    id: 10,
    name: 'Carl Carlson',
    phone: '3405337834',
    email: 'carlcarlson@example.com',
    relation: ' ',
    invited: ' ',
},  {
    id: 11,
    name: 'Barry Allen',
    phone: '2104378228',
    email: 'fastestmanalive@example.com',
    relation: ' ',
    invited: ' ',
},  {
    id: 12,
    name: 'Michael Scott',
    phone: '5703249385',
    email: 'michaelscott@example.com',
    relation: ' ',
    invited: ' ',
},  {
    id: 13,
    name: 'Bruce Banner',
    phone: '3894223722',
    email: 'greenmonster@example.com',
    relation: ' ',
    invited: ' ',
},  {
    id: 14,
    name: 'Clark Griswold',
    phone: '2104831865',
    email: 'clarkgriswold@example.com',
    relation: ' ',
    invited: ' ',
},  {
    id: 15,
    name: 'Marshall Teach',
    phone: '3284309123',
    email: 'marshallteach@example.com',
    relation: ' ',
    invited: ' ',
},  {
    id: 16,
    name: 'Luke Skywalker',
    phone: '3258940343',
    email: 'lukeskywalker@example.com',
    relation: ' ',
    invited: ' ',
},  {
    id: 17,
    name: 'Linnea Alvinquist',
    phone: '2343549565',
    email: 'linneaalvinquist@example.com',
    relation: ' ',
    invited: ' ',
},  {
    id: 18,
    name: 'Sheldon Cooper',
    phone: '7403943821',
    email: 'sheldoncooper@example.com',
    relation: ' ',
    invited: ' ',
},  {
    id: 19,
    name: 'Luke Segars',
    phone: '8432385340',
    email: 'luke@example.com',
    relation: ' ',
    invited: ' ',
}];
